dist: trusty
sudo: required

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
  
addons:
  sonarcloud:
    organization: "foissac-nicola-github" # the key of the org you chose at step #3
    token: SONARD_CLOUD

matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r Scrapper/requirements.txt
      stages:
        - Tests
        - Quality
      jobs:
        include :
          - stage: Tests
            name: "Unit Tests" 
            script: skip
          - stage: Quality
            name: "Run Sonar Cloud" 
            script: 
              - sonar-scanner
      

