dist: trusty
sudo: required

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
  
   
matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r Scrapper/requirements.txt
      script: skip
      stage: Tests
      name: "Unit Tests"
      
    - language: python
      python: 3.6
      stage: Quality
      name: "Run Sonar Cloud"
      addons:
        sonarcloud:
        organization: "foissac-nicola-github" # the key of the org you chose at step #3
      script:
        - cd Scrapper
        - sonar-scanner -Dsonar.login=${SONAR_CLOUD} -Dsonar.projectKey=Foissac-Nicola_Accidentology-Manager -Dsonar.projectName=Accidentology-Manager -Dsonar.projectVersion=0.1 -Dsonar.links.homepage=https://github.com/Foissac-Nicola/Accidentology-Manager -Dsonar.links.ci=https://travis-ci.com/Foissac-Nicola/Accidentology-Manager -Dsonar.links.scm=https://github.com/Foissac-Nicola/Accidentology-Manager -Dsonar.links.issue=https://github.com/Foissac-Nicola/Accidentology-Manager/issues -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=Scrapper -Dsonar.language=py -Dsonar.sourceEncoding=UTF-8 -Dsonar.branch=${TRAVIS_BRANCH} -Dsonar.organization=foissac-nicola-github


      

